version: "2"

services:
  mail:
    build: mail
    ports:
    - "25:25"
    - "110:110"
    volumes:
    - "./config.json:/app/config.json"
  
  web:
    build: web
    volumes:
    - "./config.json:/var/config.json"
    extra_hosts:
    - "smtp-server:10.77.2.2"
  
  cron:
    build: app
    volumes:
    - "./config.json:/app/config.json"
  
  nginx:
    image: nginx:alpine
    ports:
    - "80:80"
    volumes:
    - "./web/htdocs:/var/www/htdocs:ro"
    - "./web/nginx.docker.conf:/etc/nginx/conf.d/default.conf:ro"