version: "2"

services:
  mail:
    build: mail
    ports:
    - "25:25"
    - "110:110"
    volumes:
    - "./config.json:/app/config.json"

  cron:
    build: app
    volumes:
    - "./config.json:/app/config.json"
  
  web:
    build:
      context: web
      dockerfile: docker/php.dockerfile
    volumes:
    - "./config.json:/var/config.json"
    extra_hosts:
    # sendmail requires valid SMTP server for sign-up
    - "smtp-server:10.77.2.2"
  
  nginx:
    build:
      context: web
      dockerfile: docker/nginx.dockerfile
    ports:
    - "80:80"

  # Comment this section to use external DB
  mariadb:
    image: mariadb
    environment:
    - MYSQL_USER
    - MYSQL_PASSWORD
    - MYSQL_DATABASE
    - MYSQL_ROOT_PASSWORD
    # Uncomment for access to mysql outside of compose stack
    #ports:
    #- "3306:3306"
    volumes:
    - "db:/var/lib/mysql"
    - "./tables.sql:/docker-entrypoint-initdb.d/1_tables.sql"
      
volumes:
  db: